name: recipes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.0+17
  cloud_firestore: ^0.12.7
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.11.1+11
  firebase_storage: ^3.0.3
  date_format: ^1.0.6
  intl: ^0.15.8
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.2.5
  path_provider: ^1.1.2
  google_maps_flutter: ^0.5.19+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true